apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elastic-system
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.13
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
          resources:
            limits:
              memory: 200Mi
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
